protected/models/ContactForm.php
<?php

/**
 * ContactForm class.
 * ContactForm is the data structure for keeping
 * contact form data. It is used by the 'contact' action of 'SiteController'.
 */
class ContactForm extends CFormModel
{
	public $name;
	public $email;
	public $subject;
	public $body;
	public $verifyCode;

	/**
	 * Declares the validation rules.
	 */
	public function rules()
	{
		return array(
			// name, email, subject and body are required
			array('name, email, subject, body', 'required'),
			// email has to be a valid email address
			array('email', 'email'),
			// verifyCode needs to be entered correctly
			array('verifyCode', 'captcha', 'allowEmpty'=>!CCaptcha::checkRequirements()),
		);
	}

	/**
	 * Declares customized attribute labels.
	 * If not declared here, an attribute would have a label that is
	 * the same as its name with the first letter in upper case.
	 */
	public function attributeLabels()
	{
		return array(
			'verifyCode'=>'Verification Code',
		);
	}
}

protected/models/LoginForm.php
<?php

/**
 * LoginForm class.
 * LoginForm is the data structure for keeping
 * user login form data. It is used by the 'login' action of 'SiteController'.
 */
class LoginForm extends CFormModel
{
	public $username;
	public $password;
	public $rememberMe;

	private $_identity;

	/**
	 * Declares the validation rules.
	 * The rules state that username and password are required,
	 * and password needs to be authenticated.
	 */
	public function rules()
	{
		return array(
			// username and password are required
			array('username, password', 'required'),
			// rememberMe needs to be a boolean
			array('rememberMe', 'boolean'),
			// password needs to be authenticated
			array('password', 'authenticate'),
		);
	}

	/**
	 * Declares attribute labels.
	 */
	public function attributeLabels()
	{
		return array(
			'rememberMe'=>'Remember me next time',
		);
	}

	/**
	 * Authenticates the password.
	 * This is the 'authenticate' validator as declared in rules().
	 */
	public function authenticate($attribute,$params)
	{
		if(!$this->hasErrors())
		{
			$this->_identity=new UserIdentity($this->username,$this->password);
			if(!$this->_identity->authenticate())
				$this->addError('password','Incorrect username or password.');
		}
	}

	/**
	 * Logs in the user using the given username and password in the model.
	 * @return boolean whether login is successful
	 */
	public function login()
	{
		if($this->_identity===null)
		{
			$this->_identity=new UserIdentity($this->username,$this->password);
			$this->_identity->authenticate();
		}
		if($this->_identity->errorCode===UserIdentity::ERROR_NONE)
		{
			$duration=$this->rememberMe ? 3600*24*30 : 0; // 30 days
			Yii::app()->user->login($this->_identity,$duration);
			return true;
		}
		else
			return false;
	}
}

protected/models/osobyFormularz.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of osobyFormularz
 *                                                                                                                                                                       
 * @author kostyszyn
 */
class osobyFormularz extends CActiveRecord{
    public $id;
    public $imie;
    public $nazwisko;
    public $plec;
    public $edukacja;
    public $obywatelstwo;
    
    public static function model($className=__CLASS__){
        return parent::model($className);
    }
    
    public function tableName(){
        return 'osoby';
    }
    
    public function attributeLabels(){
        return array(
            'id'=>'ID',
            'imie'=>'Imię',
            'nazwisko'=>'Nazwisko',
            'plec'=>'Płeć',
            'edukacja'=>'Edukacja',
            'obywatelstwo'=>'Obywatelstwo'
        );
    }
    
    public function rules(){
        return array(
            array('imie',  'required'),
            array('nazwisko',  'required'),
            array('plec',  'required'),
            array('edukacja',  'required'),
            array('obywatelstwo',  'required'),
        );
    }
    
    
}

protected/controllers/SiteController.php
<?php

class SiteController extends Controller {

    /**
     * Declares class-based actions.
     */
    public function actions() {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex() {
        $this->render('index');
    }

   
    
    
    public function actionWyniki() {
             $Dane = new CActiveDataProvider('osobyFormularz', array(
                 'Pagination' => array (
                  'PageSize' =>5 
              ),
             ));

  $this->render('wyniki',array(
      'Dane'=>$Dane,
  ));
    }

    public function actionAnkieta() {        
                $Modelosoby = new osobyFormularz;
        if(isset($_POST['osobyFormularz'])){
            $Modelosoby->attributes = $_POST['osobyFormularz'];
            if($Modelosoby->validate()){
                if($Modelosoby->obywatelstwo!=='')
                                $Modelosoby->obywatelstwo=implode(',',$Modelosoby->obywatelstwo);//converting to string...
                if($Modelosoby->edukacja!=='')
                                $Modelosoby->edukacja=implode(',',$Modelosoby->edukacja);
                if ($Modelosoby->save())
                    $this->redirect('index.php?r=site/wyniki');

            }
        }
        $this->render('formularz', array(
            'model'=>$Modelosoby,
        ));
        
        
        
        
    }

}
?>

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
	</div><!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Start', 'url'=>array('/site/index')),
				array('label'=>'Ankieta', 'url'=>array('/site/ankieta')),
				array('label'=>'Wyniki', 'url'=>array('/site/wyniki')),
			),
		)); ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> by My Company.<br/>
		All Rights Reserved.<br/>
		<?php echo Yii::powered(); ?>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>

protected/views/site/error.php
<?php
/* @var $this SiteController */
/* @var $error array */

$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<h2>Error <?php echo $code; ?></h2>

<div class="error">
<?php echo CHtml::encode($message); ?>
</div>

protected/views/site/formularz.php
<div class="form" style="padding: 15px;">

<?php $form=$this->beginWidget('CActiveForm', array(
    'id'=>'formularz',
    'enableAjaxValidation'=>false,)); ?>
<p class="note">Pola oznaczone<span class="required">*</span> sa wymagane.</p>

<?php echo $form->errorSummary($model); ?>

<div class="row">
    <?php echo $form->labelEx($model,'imie'); ?>
    <?php echo $form->textField($model,'imie'); ?>
    <?php echo $form->error($model,'imie'); ?>
</div>

<div class="row">
    <?php echo $form->labelEx($model,'nazwisko'); ?>
    <?php echo $form->textField($model,'nazwisko'); ?>
    <?php echo $form->error($model,'nazwisko'); ?>
</div>
<div><b>Płeć :</b></div>
<div class="row">
    <?php echo $form->radioButton($model,'plec',
            array(
        'man'=> 'mężczyzna',
    )); ?> Mężczyzna
</div>

<div class="row">
    <?php echo $form->radioButton($model,'plec',
            array(
        'woman'=> 'kobieta',
    )); ?> Kobieta
</div>


<div><b>Obywatelstwo :</b></div>

<?php 
echo CHtml::activeCheckboxList(
  $model, 'obywatelstwo', 
  array('pl'=>'Polskie', 'ang'=>'Angielskie','inne'=>'Inne'),
  array('template'=>'<li>{input} {label}</li>',)
);
?>

<div><b>Edukacja :</b></div>

<?php 
echo CHtml::activeCheckboxList(
  $model, 'edukacja', 
  array('pod'=>'Podstawowe', 'mid'=>'Średnie','high'=>'Wyższe'),
  array('template'=>'<li>{input} {label}</li>',)
);
?>


<div class="row buttons">
    <?php echo CHtml::submitButton('Dodaj'); ?>
</div>

<?php $this->endWidget(); ?>
</div>

protected/views/site/index.php
<?php
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name;
?>

<img src="http://kaelmo-test.pl/images/kaelmo.png" >
<img src="http://kaelmo-test.pl/images/why.jpg" >

<p>START</p>

<p>"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>

<p>"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>

protected/views/site/pages/about.php
<?php
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name . ' - About';
$this->breadcrumbs=array(
	'About',
);
?>
<h1>About</h1>

<p>This is a "static" page. You may change the content of this page
by updating the file <code><?php echo __FILE__; ?></code>.</p>

protected/views/site/wyniki.php
<?php
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name;
?>
<?php $form=$this->beginWidget('CActiveForm', array(
    'id'=>'wyniki',
    'enableAjaxValidation'=>false,)); ?>

<h1>Welcome to <i><?php echo CHtml::encode(Yii::app()->name); ?></i></h1>
<?php
$this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider'=>$Dane,
))
?> 
<?php $this->endWidget(); ?>